language: go
node_js:
- 1.13
script:
- make
- eval "$(ssh-agent -s)"
- ssh-keyscan -H 95.163.212.32 >> ~/.ssh/known_hosts
- chmod 400 $HOME/.ssh/deploy-2019-2-mGznqKVh.pem
- scp -i $HOME/.ssh/deploy-2019-2-mGznqKVh.pem -r ./bin/* ubuntu@95.163.212.32:/home/ubuntu/beepteam-server
- ssh -i $HOME/.ssh/deploy-2019-2-mGznqKVh.pem ubuntu@95.163.212.32 '/home/ubuntu/beepteam-server/app &'
before_install:
- openssl aes-256-cbc -K $encrypted_c66004758dd4_key -iv $encrypted_c66004758dd4_iv
  -in deploy-2019-2-mGznqKVh.pem.enc -out $HOME/.ssh/deploy-2019-2-mGznqKVh.pem
  -d